# Generated by Django 5.0.6 on 2024-05-12 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Costomer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.DecimalField(decimal_places=2, max_digits=100)),
                ('phone', models.DecimalField(decimal_places=2, max_digits=100)),
            ],
        ),
    ]
